/* Manual, encrypted, whole-device data transfer. No server is involved. */
(()=>{'use strict';
 const VERSION=1, PREFIX='miik-', encoder=new TextEncoder(), decoder=new TextDecoder();
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const acceptable=k=>/^(miik|MIIK)/i.test(k)||['schoolName','regionName','counselorName'].includes(k);
 const bytes=b=>{let s='';for(let i=0;i<b.length;i+=8192)s+=String.fromCharCode(...b.subarray(i,i+8192));return btoa(s)}, unbytes=s=>Uint8Array.from(atob(s),x=>x.charCodeAt(0));
 const count=(entries,key)=>{try{const a=JSON.parse(entries[key]||'[]');return Array.isArray(a)?a.length:0}catch(_){return 0}};
 function snapshot(){const data=Object.create(null);for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&acceptable(k))data[k]=localStorage.getItem(k)}return{format:'miik-manual-backup',version:VERSION,createdAt:new Date().toISOString(),entries:data}}
 async function secret(password,salt){const material=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
 async function encrypt(data,password){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await secret(password,salt),encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,encoder.encode(JSON.stringify(data)));return JSON.stringify({format:'miik-encrypted-backup',version:VERSION,salt:bytes(salt),iv:bytes(iv),data:bytes(new Uint8Array(encrypted))})}
 async function decrypt(input,password){const box=JSON.parse(input);if(box?.format!=='miik-encrypted-backup'||box.version!==VERSION||!box.salt||!box.iv||!box.data)throw Error('invalid-format');const key=await secret(password,unbytes(box.salt)),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unbytes(box.iv)},key,unbytes(box.data));const payload=JSON.parse(decoder.decode(plain));if(payload?.format!=='miik-manual-backup'||payload.version!==VERSION||!payload.entries||typeof payload.entries!=='object'||Array.isArray(payload.entries))throw Error('invalid-data');if(!Object.keys(payload.entries).every(k=>acceptable(k)&&typeof payload.entries[k]==='string'))throw Error('invalid-keys');return payload}
 function download(contents,name){const url=URL.createObjectURL(new Blob([contents],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();setTimeout(()=>{a.remove();URL.revokeObjectURL(url)},60000)}
 let candidate=null,safetyReady=false;
 function status(message,bad=false){const box=document.getElementById('miikBackupStatus');if(box){box.textContent=message;box.classList.toggle('bad',bad)}}
 window.miikBackupOpen=function(){candidate=null;safetyReady=false;window.openModule('النسخ الاحتياطي ونقل البيانات','احفظ نسخة مشفّرة وانقلها يدويًا بين جوالك وجهازك.');const grid=document.getElementById('moduleGrid');grid.innerHTML=`<section class="miik-backup-panel"><h3>تنزيل نسخة من هذا الجهاز</h3><p>أدخل رمزًا تختاره. ستحتاج إليه لاستعادة الملف، ولا يمكن استرجاع البيانات بدونه.</p><label>رمز النسخة <input id="miikBackupPassword" type="password" autocomplete="new-password" minlength="8" placeholder="٨ أحرف على الأقل"></label><button type="button" onclick="miikBackupExport()">تنزيل نسخة مشفّرة</button><hr><h3>استعادة نسخة على هذا الجهاز</h3><p>الاستعادة تستبدل بيانات مِعِك الحالية هنا بالكامل. لا تدمج سجلات الجهازين.</p><label>اختر ملف النسخة <input id="miikBackupFile" type="file" accept=".json,application/json"></label><label>رمز الملف <input id="miikRestorePassword" type="password" autocomplete="off"></label><button type="button" onclick="miikBackupPreview()">فحص الملف ومعاينته</button><div id="miikBackupPreview"></div><div id="miikBackupStatus" role="status"></div></section>`};
 window.miikBackupExport=async function(){const pw=document.getElementById('miikBackupPassword')?.value||'';if(pw.length<8)return status('اكتب رمزًا من ٨ أحرف على الأقل.',true);try{const content=await encrypt(snapshot(),pw);download(content,'miik-backup-'+new Date().toISOString().slice(0,10)+'.json');status('بدأ تنزيل النسخة المشفّرة. تأكد من وجود الملف في التنزيلات.')}catch(e){console.error(e);status('تعذر إنشاء النسخة على هذا المتصفح.',true)}};
 window.miikBackupPreview=async function(){candidate=null;safetyReady=false;document.getElementById('miikBackupPreview').innerHTML='';const f=document.getElementById('miikBackupFile')?.files?.[0],pw=document.getElementById('miikRestorePassword')?.value||'';if(!f||!pw)return status('اختر الملف وأدخل الرمز.',true);if(f.size>32*1024*1024)return status('حجم الملف يتجاوز الحد المسموح (٣٢ ميجابايت).',true);try{candidate=await decrypt(await f.text(),pw);const e=candidate.entries,now=snapshot().entries;document.getElementById('miikBackupPreview').innerHTML=`<div class="miik-backup-review"><b>ملف النسخة: ${esc(new Date(candidate.createdAt).toLocaleString('ar-SA'))}</b><p>الملف: ${count(e,'miikStudentsV39')} طالب · ${count(e,'miik-demo-actions')} إجراء. بيانات هذا الجهاز الآن: ${count(now,'miikStudentsV39')} طالب · ${count(now,'miik-demo-actions')} إجراء.</p><p>قبل الاستبدال نزّل نسخة أمان من بيانات هذا الجهاز بالرمز نفسه واحفظها؛ ثم أكد الاستعادة.</p><button type="button" onclick="miikBackupSafety()">١. تنزيل نسخة أمان للجهاز</button><button type="button" id="miikBackupRestore" onclick="miikBackupRestore()" disabled>٢. استبدال البيانات</button></div>`;status('فُتح الملف بنجاح. راجع الأعداد والتاريخ قبل الاستعادة.')}catch(e){console.error(e);status('تعذر فتح الملف: الرمز غير صحيح أو الملف تالف أو غير متوافق.',true)}};
 window.miikBackupSafety=async function(){if(!candidate)return;try{const pw=document.getElementById('miikRestorePassword')?.value||'';if(pw.length<8)return status('أدخل رمزًا من ٨ أحرف على الأقل لنسخة الأمان.',true);download(await encrypt(snapshot(),pw),'miik-before-restore-'+new Date().toISOString().slice(0,10)+'.json');safetyReady=true;document.getElementById('miikBackupRestore').disabled=false;status('بدأ تنزيل نسخة الأمان. تأكد من حفظها قبل الاستبدال.')}catch(e){console.error(e);status('تعذر تنزيل نسخة الأمان.',true)}};
 window.miikBackupRestore=function(){if(!candidate||!safetyReady)return;const entries=candidate.entries;showMiikDialog(`<h2>تأكيد استبدال بيانات هذا الجهاز</h2><p>ستُزال بيانات مِعِك الحالية من هذا المتصفح وتُستبدل ببيانات الملف. هل أنت متأكد أنك حفظت نسخة الأمان؟</p><div class="dialog-actions"><button type="button" class="dialog-primary" id="miikBackupConfirm">نعم، استبدال</button><button type="button" class="dialog-cancel" onclick="closeMiikDialog()">إلغاء</button></div>`);document.getElementById('miikBackupConfirm').onclick=()=>{const before=snapshot().entries;try{Object.keys(before).forEach(k=>localStorage.removeItem(k));Object.entries(entries).forEach(([k,v])=>localStorage.setItem(k,v));candidate=null;closeMiikDialog();showMiikNotice?.('اكتملت الاستعادة','أُعيدت بيانات الملف. ستُحدَّث الصفحة الآن.');setTimeout(()=>location.reload(),850)}catch(e){try{Object.keys(entries).forEach(k=>localStorage.removeItem(k));Object.entries(before).forEach(([k,v])=>localStorage.setItem(k,v))}catch(rollbackError){console.error('Backup rollback failed',rollbackError)}closeMiikDialog();status('تعذرت الاستعادة. أعيدت البيانات السابقة قدر الإمكان؛ احتفظ بنسخة الأمان.',true);console.error(e)}}};
})();
