/* Manual, encrypted, whole-device data transfer. No server is involved. */
(()=>{'use strict';
 const VERSION=1, PREFIX='miik-', encoder=new TextEncoder(), decoder=new TextDecoder();
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const acceptable=k=>/^(miik|MIIK)/i.test(k)||['schoolName','regionName','counselorName'].includes(k);
 const bytes=b=>{let s='';for(let i=0;i<b.length;i+=8192)s+=String.fromCharCode(...b.subarray(i,i+8192));return btoa(s)}, unbytes=s=>Uint8Array.from(atob(s),x=>x.charCodeAt(0));
 const count=(entries,key)=>{try{const a=JSON.parse(entries[key]||'[]');return Array.isArray(a)?a.length:0}catch(_){return 0}};
 function snapshot(){const data=Object.create(null);for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&acceptable(k))data[k]=localStorage.getItem(k)}return{format:'miik-manual-backup',version:VERSION,createdAt:new Date().toISOString(),entries:data}}
 async function secret(password,salt){const material=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
 async function encrypt(data,password){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await secret(password,salt),encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,encoder.encode(JSON.stringify(data)));return JSON.stringify({format:'miik-encrypted-backup',version:VERSION,salt:bytes(salt),iv:bytes(iv),data:bytes(new Uint8Array(encrypted))})}
 async function decrypt(input,password){const box=JSON.parse(input);if(box?.format!=='miik-encrypted-backup'||box.version!==VERSION||!box.salt||!box.iv||!box.data)throw Error('invalid-format');const key=await secret(password,unbytes(box.salt)),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unbytes(box.iv)},key,unbytes(box.data));const payload=JSON.parse(decoder.decode(plain));if(payload?.format!=='miik-manual-backup'||payload.version!==VERSION||!payload.entries||typeof payload.entries!=='object'||Array.isArray(payload.entries))throw Error('invalid-data');if(!Object.keys(payload.entries).every(k=>acceptable(k)&&typeof payload.entries[k]==='string'))throw Error('invalid-keys');return payload}
 function download(contents,name){const url=URL.createObjectURL(new Blob([contents],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();setTimeout(()=>{a.remove();URL.revokeObjectURL(url)},60000)}

 const plain=x=>x!==null&&typeof x==='object'&&!Array.isArray(x);
 const canon=x=>Array.isArray(x)?'['+x.map(canon).join(',')+']':plain(x)?'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canon(x[k])).join(',')+'}':JSON.stringify(x);
 const parse=x=>{try{return JSON.parse(x)}catch(_){return x}};
 const studentKey=x=>['name','stage','grade','section'].map(k=>String(x?.[k]||'').replace(/\s+/g,' ').trim()).join('|');
 const recordId=x=>plain(x)?(['miikId','_v55id','id','uid'].find(k=>x[k]!=null&&x[k]!=='')||''):'';
 function fallbackRecord(row,key){if(!plain(row))return '';if(/^miikExec_/.test(key)&&row.date&&row.execTitle)return 'execution:'+row.date+'|'+row.execTitle;if(/^miikCouncil_/.test(key)&&row.date&&row.topic)return 'meeting:'+row.date+'|'+row.topic;return ''}
 function mergePlan(current,incoming,choices={}){
  const conflicts=[],stats={added:0},ids=new Map(),src=JSON.parse(JSON.stringify(incoming));
  const localStudents=parse(current.miikStudentsV39||'[]'),remoteStudents=parse(src.miikStudentsV39||'[]');
  if(Array.isArray(localStudents)&&Array.isArray(remoteStudents))for(const r of remoteStudents){const matches=localStudents.filter(l=>studentKey(l)===studentKey(r));if(r.miikId&&matches.length===1&&matches[0].miikId&&r.name&&r.grade){ids.set(r.miikId,matches[0].miikId);r.miikId=matches[0].miikId}}
  function remap(x,k=''){if(Array.isArray(x))return x.map(v=>remap(v,k));if(plain(x)){const out=Object.create(null);for(const [a,b]of Object.entries(x))out[a]=remap(b,a);return out}return typeof x==='string'&&/^(studentId|miikId|groupStudentIds|studentIds)$/.test(k)&&ids.has(x)?ids.get(x):x}
  for(const k of Object.keys(src)){const v=parse(src[k]);if(typeof v==='object'&&v!==null)src[k]=JSON.stringify(remap(v))}
  function conflict(a,b,path,label){const id=JSON.stringify(path);conflicts.push({id,label,current:a,incoming:b});return choices[id]==='incoming'?b:a}
  function merge(a,b,path,label){
   if(canon(a)===canon(b))return a;
   if(Array.isArray(a)&&Array.isArray(b)){
    // Ordered field arrays (form values) must remain one coherent value.
    if(path[path.length-1]==='values')return conflict(a,b,path,label);
    const out=a.slice();for(const row of b){if(out.some(x=>canon(x)===canon(row)))continue;const field=recordId(row);const fallback=fallbackRecord(row,path[0]);const matches=field?out.map((x,i)=>plain(x)&&x[field]===row[field]?i:-1).filter(i=>i>=0):fallback?out.map((x,i)=>fallbackRecord(x,path[0])===fallback?i:-1).filter(i=>i>=0):[];const i=matches.length===1?matches[0]:-1;if(i<0){out.push(row);stats.added++}else out[i]=merge(out[i],row,path.concat('record:'+(field?field+':'+row[field]:fallback)),row.name||row.student||row.title||label)}return out;
   }
   if(plain(a)&&plain(b)){const out=Object.create(null);for(const [k,v]of Object.entries(a))out[k]=v;for(const [k,v]of Object.entries(b)){if(!Object.prototype.hasOwnProperty.call(out,k)){out[k]=v;stats.added++}else out[k]=merge(out[k],v,path.concat(k),label)}return out}
   return conflict(a,b,path,label);
  }
  const entries={...current};for(const [k,v]of Object.entries(src)){if(!(k in current)){entries[k]=v;stats.added++;continue}const a=parse(current[k]),b=parse(v);let json=true;try{JSON.parse(current[k]);JSON.parse(v)}catch(_){json=false}const merged=merge(a,b,[k],keyLabel(k));entries[k]=json?JSON.stringify(merged):typeof merged==='string'?merged:JSON.stringify(merged)}
  return{entries,conflicts,stats};
 }
 function keyLabel(k){return({'miikStudentsV39':'بيانات الطلاب','miik-demo-actions':'سجلات الإجراءات','miikV56Special':'الفئات الخاصة','miikProgramReportNotesV1':'تقييم البرامج','miik-group-guidance-v1':'التوجيه الجماعي'})[k]||(/council|مجلس/i.test(k)?'المجلس الطلابي':/program/i.test(k)?'البرامج':/plan/i.test(k)?'الخطة':'بيانات مِعِك')}
 window.miikBackupMergePlan=mergePlan;
 let candidate=null,safetyReady=false,safetySnapshot=null,mergeBase=null,plan=null;
 function status(message,bad=false){const box=document.getElementById('miikBackupStatus');if(box){box.textContent=message;box.classList.toggle('bad',bad)}}
 window.miikBackupOpen=function(){candidate=null;safetyReady=false;window.openModule('النسخ الاحتياطي ونقل البيانات','احفظ نسخة مشفّرة وانقلها يدويًا بين جوالك وجهازك.');const grid=document.getElementById('moduleGrid');grid.innerHTML=`<section class="miik-backup-panel"><h3>تنزيل نسخة من هذا الجهاز</h3><p>أدخل رمزًا تختاره. ستحتاج إليه لاستعادة الملف، ولا يمكن استرجاع البيانات بدونه.</p><label>رمز النسخة <input id="miikBackupPassword" type="password" autocomplete="new-password" minlength="8" placeholder="٨ أحرف على الأقل"></label><button type="button" onclick="miikBackupExport()">تنزيل نسخة مشفّرة</button><hr><h3>استعادة نسخة على هذا الجهاز</h3><p>اختر دمج أعمال الجهازين مع الحفاظ على الموجود، أو استبدال بيانات الجهاز بالكامل.</p><label>طريقة الاستيراد <select id="miikBackupMode"><option value="merge">دمج مع البيانات الحالية</option><option value="replace">استبدال البيانات بالكامل</option></select></label><label>اختر ملف النسخة <input id="miikBackupFile" type="file" accept=".json,application/json"></label><label>رمز الملف <input id="miikRestorePassword" type="password" autocomplete="off"></label><button type="button" onclick="miikBackupPreview()">فحص الملف ومعاينته</button><div id="miikBackupPreview"></div><div id="miikBackupStatus" role="status"></div></section>`};
 window.miikBackupExport=async function(){const pw=document.getElementById('miikBackupPassword')?.value||'';if(pw.length<8)return status('اكتب رمزًا من ٨ أحرف على الأقل.',true);try{const content=await encrypt(snapshot(),pw);download(content,'miik-backup-'+new Date().toISOString().slice(0,10)+'.json');status('بدأ تنزيل النسخة المشفّرة. تأكد من وجود الملف في التنزيلات.')}catch(e){console.error(e);status('تعذر إنشاء النسخة على هذا المتصفح.',true)}};
 window.miikBackupPreview=async function(){candidate=null;safetyReady=false;document.getElementById('miikBackupPreview').innerHTML='';const f=document.getElementById('miikBackupFile')?.files?.[0],pw=document.getElementById('miikRestorePassword')?.value||'';if(!f||!pw)return status('اختر الملف وأدخل الرمز.',true);if(f.size>32*1024*1024)return status('حجم الملف يتجاوز الحد المسموح (٣٢ ميجابايت).',true);try{candidate=await decrypt(await f.text(),pw);mergeBase=snapshot().entries;const e=candidate.entries,now=snapshot().entries;document.getElementById('miikBackupPreview').innerHTML=`<div class="miik-backup-review"><b>ملف النسخة: ${esc(new Date(candidate.createdAt).toLocaleString('ar-SA'))}</b><p>الملف: ${count(e,'miikStudentsV39')} طالب · ${count(e,'miik-demo-actions')} إجراء. بيانات هذا الجهاز الآن: ${count(now,'miikStudentsV39')} طالب · ${count(now,'miik-demo-actions')} إجراء.</p><p>نزّل نسخة أمان من بيانات هذا الجهاز بالرمز نفسه واحفظها؛ ثم نفّذ الاستيراد.</p><button type="button" onclick="miikBackupSafety()">١. تنزيل نسخة أمان للجهاز</button><button type="button" id="miikBackupRestore" onclick="miikBackupRestore()" disabled>٢. تنفيذ الاستيراد</button></div>`;document.getElementById('miikBackupMode').onchange=miikBackupReviewMerge;miikBackupReviewMerge();status('فُتح الملف بنجاح. راجع البيانات قبل الاستيراد.')}catch(e){console.error(e);status('تعذر فتح الملف: الرمز غير صحيح أو الملف تالف أو غير متوافق.',true)}};
 window.miikBackupSafety=async function(){if(!candidate)return;try{const pw=document.getElementById('miikRestorePassword')?.value||'';if(pw.length<8)return status('أدخل رمزًا من ٨ أحرف على الأقل لنسخة الأمان.',true);safetySnapshot=snapshot();download(await encrypt(safetySnapshot,pw),'miik-before-restore-'+new Date().toISOString().slice(0,10)+'.json');safetyReady=true;document.getElementById('miikBackupRestore').disabled=false;status('بدأ تنزيل نسخة الأمان. تأكد من حفظها قبل الاستيراد.')}catch(e){console.error(e);status('تعذر تنزيل نسخة الأمان.',true)}};

 window.miikBackupReviewMerge=function(){
  document.getElementById('miikBackupConflicts')?.remove();if(!candidate||document.getElementById('miikBackupMode').value!=='merge')return;
  plan=mergePlan(mergeBase,candidate.entries);const box=document.createElement('div');box.id='miikBackupConflicts';
  box.innerHTML=`<h3>مراجعة الدمج</h3><p>تُضاف الأعمال الجديدة دون حذف الموجودة. السجلات المتطابقة لا تتكرر. اختلافات تحتاج اختيارك: ${plan.conflicts.length}.</p>`+plan.conflicts.map((c,i)=>`<div class="miik-backup-conflict"><b>${esc(c.label)}</b><p>الموجود بالجهاز:</p><pre>${esc(typeof c.current==='string'?c.current:JSON.stringify(c.current,null,2))}</pre><p>الموجود بالملف:</p><pre>${esc(typeof c.incoming==='string'?c.incoming:JSON.stringify(c.incoming,null,2))}</pre><label>النسخة المعتمدة <select id="miikMergeChoice${i}"><option value="">اختر بعد المراجعة</option><option value="current">إبقاء الموجود بالجهاز</option><option value="incoming">اعتماد الموجود بالملف</option></select></label></div>`).join('');
  document.getElementById('miikBackupPreview').appendChild(box);
 };
 window.miikBackupRestore=function(){
  if(!candidate||!safetyReady)return;const merging=document.getElementById('miikBackupMode').value==='merge';
  if(canon(snapshot().entries)!==canon(mergeBase)||canon(safetySnapshot?.entries)!==canon(mergeBase))return status('تغيرت بيانات الجهاز بعد المعاينة. أعد فحص الملف وتنزيل نسخة الأمان قبل الاستيراد.',true);
  const choices={};if(merging){for(let i=0;i<plan.conflicts.length;i++){const v=document.getElementById('miikMergeChoice'+i)?.value;if(!v)return status('اختر النسخة المعتمدة لكل اختلاف قبل الدمج.',true);choices[plan.conflicts[i].id]=v}}
  const entries=merging?mergePlan(mergeBase,candidate.entries,choices).entries:candidate.entries;
  showMiikDialog(`<h2>${merging?'تأكيد دمج بيانات الجهازين':'تأكيد استبدال بيانات هذا الجهاز'}</h2><p>${merging?'ستُضاف الأعمال الجديدة وتُطبّق اختياراتك للاختلافات. تبقى السجلات الحالية التي لا يوجد لها مقابل في الملف.':'ستُزال بيانات مِعِك الحالية وتُستبدل ببيانات الملف.'} تأكد من حفظ نسخة الأمان.</p><div class="dialog-actions"><button type="button" class="dialog-primary" id="miikBackupConfirm">${merging?'نعم، دمج البيانات':'نعم، استبدال'}</button><button type="button" class="dialog-cancel" onclick="closeMiikDialog()">إلغاء</button></div>`);
  document.getElementById('miikBackupConfirm').onclick=()=>{const before=snapshot().entries;if(canon(before)!==canon(mergeBase)){closeMiikDialog();return status('تغيرت البيانات. أعد المعاينة أولاً.',true)}try{if(!merging)Object.keys(before).forEach(k=>localStorage.removeItem(k));Object.entries(entries).forEach(([k,v])=>localStorage.setItem(k,v));candidate=null;safetyReady=false;closeMiikDialog();showMiikNotice?.('اكتمل الاستيراد',merging?'دُمجت الأعمال. ستُحدَّث الصفحة الآن.':'أُعيدت بيانات الملف. ستُحدَّث الصفحة الآن.');setTimeout(()=>location.reload(),850)}catch(e){try{Object.keys(entries).forEach(k=>localStorage.removeItem(k));Object.entries(before).forEach(([k,v])=>localStorage.setItem(k,v))}catch(rollbackError){console.error('Backup rollback failed',rollbackError)}closeMiikDialog();status('تعذر الاستيراد. أعيدت البيانات السابقة قدر الإمكان؛ احتفظ بنسخة الأمان.',true);console.error(e)}};
 };
})();
